sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t gee9328/docekr-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true gee9328/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-911495380316"
  bucker_path: "docker-react-app"
  on:
    branch: master